dependencies:
- name: demo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.19
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: ext-jacoco
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.36
- name: ext-java-code-quality
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.23
